language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi
  - composer show
  - composer global require friendsofphp/php-cs-fixer:@stable
  - export PHP_CS_FIXER="~/.composer/vendor/bin/php-cs-fixer"

before_script:
  - if [[ "$DEPENDENCIES" = 'low' ]]; then export PHP_ARGS=$(php -r "echo '-d error_reporting=', E_ALL ^ (E_DEPRECATED | E_USER_DEPRECATED);"); else export PHP_ARGS=''; fi

script:
  - php -n ${PHP_CS_FIXER} --diff --dry-run -v fix
  - php ${PHP_ARGS} vendor/bin/phpunit
  - php ${PHP_ARGS} vendor/bin/behat
  - php -n ${PHP_ARGS} speedtest/console.php test-links
  - php examples/micro-framework.php
  - php examples/months.php
  - php examples/symfony.php
  - php examples/transform-params.php

after_script:
  - travis_retry bin/coveralls.sh
